from django.urls import path
from django.contrib import admin
from sisdespenda.views import inicial, login_logout, tipo_renda, renda, despesa, tipo_despesa, despesa_relatorio, \
    renda_relatorio, relacao_relatorio, evento, saldo, despesa_grafico, recorrencia_despesa

urlpatterns = [
    path('onsisdespenda/acc/admin/', admin.site.urls),
    path('', inicial.inicio, name='inicio'),
    path('accounts/login/', login_logout.login_req, name='login_req'),
    path('entrar/', login_logout.login_user),
    path('logout/', login_logout.logout_user),
    path('tipo/lista', tipo_renda.tipo_renda_list, name='tipo_renda_list'),
    path('tipo/novo/', tipo_renda.tipo_renda_new, name='tipo_renda_new'),
    path('tipo/novo/<int:pk>', tipo_renda.tipo_renda_update, name='tipo_renda_update'),
    path('tipo/editar/<int:pk>', tipo_renda.tipo_renda_edit, name='tipo_renda_edit'),
    path('tipo/despesa/lista', tipo_despesa.tipo_despesa_list, name='tipo_despesa_list'),
    path('tipo/despesa/novo/', tipo_despesa.tipo_despesa_new, name='tipo_despesa_new'),
    path('tipo/despesa/novo/<int:pk>', tipo_despesa.tipo_despesa_update, name='tipo_despesa_update'),
    path('tipo/despesa/editar/<int:pk>', tipo_despesa.tipo_despesa_edit, name='tipo_despesa_edit'),
    path('renda/lista', renda.renda_list, name='renda_list'),
    path('renda/novo/', renda.renda_new, name='renda_new'),
    path('renda/novo/<int:pk>', renda.renda_update, name='renda_update'),
    path('renda/editar/<int:pk>', renda.renda_edit, name='renda_edit'),
    path('renda/lista/ano/<int:ano>', renda.renda_list_param, name='renda_list_param'),
    path('renda/remove/<int:pk>', renda.renda_remove, name='renda_remove'),
    path('recorrencia/despesa/lista', recorrencia_despesa.recorrencia_despesa_list, name='recorrencia_despesa_list'),
    path('recorrencia/despesa/novo/', recorrencia_despesa.recorrencia_despesa_new, name='recorrencia_despesa_new'),
    path('recorrencia/despesa/novo/<int:pk>', recorrencia_despesa.recorrencia_despesa_new,
         name='recorrencia_despesa_new'),
    path('recorrencia/despesa/remove/<int:pk>', recorrencia_despesa.recorrencia_despesa_remove,
         name='recorrencia_despesa_remove'),
    path('despesa/lista', despesa.despesa_list, name='despesa_list'),
    path('despesa/novo/', despesa.despesa_new, name='despesa_new'),
    path('despesa/novo/<int:pk>', despesa.despesa_update, name='despesa_update'),
    path('despesa/editar/<int:pk>', despesa.despesa_edit, name='despesa_edit'),
    path('despesa/lista/ano/<int:ano>', despesa.despesa_list_param, name='despesa_list_param'),
    path('despesa/remove/<int:pk>', despesa.despesa_remove, name='despesa_remove'),
    path('despesa/grafico/mes/ano/', despesa_grafico.despesa_grafico_mes_ano, name='despesa_grafico_mes_ano'),
    path('despesa/grafico/mes/ano/<int:mes>', despesa_grafico.despesa_grafico_mes_ano, name='despesa_grafico_mes_ano'),
    path('despesa/grafico/ano/', despesa_grafico.despesa_grafico_ano, name='despesa_grafico_ano'),
    path('despesa/grafico/ano/<int:ano>', despesa_grafico.despesa_grafico_ano, name='despesa_grafico_ano'),
    path('despesa/grafico/mes/ano/<int:mes>/<int:indice>', despesa_grafico.despesa_grafico_mes_ano,
         name='despesa_grafico_mes_ano'),
    path('despesa/relatorio/mes/ano', despesa_relatorio.despesas_realizadas_mes_ano,
         name='despesas_realizadas_mes_ano'),
    path('despesa/relatorio/mes/ano/<int:mes>', despesa_relatorio.despesas_realizadas_mes_ano_param,
         name='despesas_realizadas_mes_ano_param'),
    path('despesa/relatorio/ano', despesa_relatorio.despesas_realizadas_ano, name='despesas_realizadas_ano'),
    path('renda/relatorio/mes/ano', renda_relatorio.rendas_realizadas_mes_ano, name='rendas_realizadas_mes_ano'),
    path('renda/relatorio/mes/ano/<int:ano>', renda_relatorio.rendas_realizadas_mes_ano_param,
         name='rendas_realizadas_mes_ano_param'),
    path('renda/relatorio/ano', renda_relatorio.rendas_realizadas_ano, name='rendas_realizadas_ano'),
    path('relacao/relatorio/mes/ano', relacao_relatorio.relacao_mes_ano, name='relacao_mes_ano'),
    path('relacao/relatorio/mes/ano/<int:ano>', relacao_relatorio.relacao_mes_ano_param, name='relacao_mes_ano_param'),
    path('relacao/relatorio/ano', relacao_relatorio.relacao_ano, name='relacao_ano'),
    path('evento/mes/ano', evento.evento_list, name='evento_list'),
    path('evento/mes/ano/<int:ano>', evento.evento_list_param, name='evento_list_param'),
    path('saldo/lista', saldo.saldo_list, name='saldo_list'),
    path('nova/senha', login_logout.set_user_password_form, name='set_user_password_form'),
    path('altera/senha/', login_logout.change_user_password, name='change_user_password'),
]
