# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaTbl',
            fields=[
                ('cd_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('vl_despesa', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('dt_despesa', models.DateTimeField()),
                ('ds_despesa', models.CharField(max_length=100)),
                ('dt_criacao', models.DateTimeField()),
                ('dt_atualizacao', models.DateTimeField()),
                ('cd_usuario', models.BigIntegerField()),
            ],
            options={
                'db_table': 'despesa_tbl',
                'verbose_name': 'Despesa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventoTbl',
            fields=[
                ('cd_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_evento', models.CharField(max_length=100)),
                ('dt_evento', models.DateTimeField()),
                ('cd_usuario', models.BigIntegerField()),
            ],
            options={
                'db_table': 'evento_tbl',
                'verbose_name': 'Evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RendaTbl',
            fields=[
                ('cd_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('vl_renda', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('dt_renda', models.DateTimeField()),
                ('dt_criacao', models.DateTimeField()),
                ('dt_atualizacao', models.DateTimeField()),
                ('cd_usuario', models.BigIntegerField()),
            ],
            options={
                'db_table': 'renda_tbl',
                'verbose_name': 'Renda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoRendaTbl',
            fields=[
                ('cd_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_tipo_renda', models.CharField(max_length=60)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('cd_usuario', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tipo_renda_tbl',
                'verbose_name': 'Tipo de renda',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rendatbl',
            name='cd_tipo_renda',
            field=models.ForeignKey(blank=True, db_column='cd_tipo_renda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sisdespenda.TipoRendaTbl'),
        ),
    ]
